# Generated by Django 4.2.6 on 2023-10-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_group_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
