# Generated by Django 4.2.6 on 2023-10-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Group name'),
        ),
    ]
